[matching_server]
endpoint = "ws://localhost:8080/matching"
[game_server]
endpoint = "ws://localhost:9090/game"
[html5_client_server]
assets_path = "/Users/tomyhero/go/src/github.com/tomyhero/battleship-game/assets"
